module "spark-master" {
  source = "modules/spark-master"
  aws_accessKey="${var.aws_accessKey}"
  aws_secretKey="${var.aws_secretKey}"
  aws_region="${var.aws_region}"
  instance_type="${var.instance_type}"
  instance_name="${var.master_machine_name}"
  aws_image_id="${var.aws_image_id}"
  iam_instance_profile="${var.iam_instance_profile}"
  security_group = "${var.security_group}"
  availability_zones  = "${var.availability_zones}"
  subnets_id="${var.subnets_id}"
  user_data = "install.sh"
  sns_topic = "${var.sns_topic}"
  root_volume_size = "${var.root_volume_size}"
  sampletag = "${var.sampletag}"
  ebs_optimized  = "${var.ebs_optimized}"
  aws_keypair_name = "${var.aws_keypair_name}"
  asg_min_size ="${var.asg_min_size}"
  asg_desired_capacity = "${var.asg_desired_capacity}"
  asg_max_size = "${var.asg_max_size}"
  yml_name = "sparkMaster.yml"
}

module "spark-slave" {
  source = "modules/spark-slave"
  aws_accessKey="${var.aws_accessKey}"
  aws_secretKey="${var.aws_secretKey}"
  aws_region="${var.aws_region}"
  instance_type="${var.instance_type}"
  instance_name="${var.slave_machine_name}"
  aws_image_id="${var.aws_image_id}"
  iam_instance_profile="${var.iam_instance_profile}"
  security_group = "${var.security_group}"
  availability_zones  = "${var.availability_zones}"
  subnets_id="${var.subnets_id}"
  user_data = "install.sh"
  sns_topic = "${var.sns_topic}"
  root_volume_size = "${var.root_volume_size}"
  sampletag = "${var.sampletag}"
  ebs_optimized  = "${var.ebs_optimized}"
  aws_keypair_name = "${var.aws_keypair_name}"
  asg_min_size ="${var.asg_min_size}"
  asg_desired_capacity = "${var.asg_desired_capacity}"
  asg_max_size = "${var.asg_max_size}"
  yml_name = "sparkSlave.yml"
  master_elb = "${module.spark-master.elb_dns}"
  # master_elb_name = "${module.spark-master.elb_name}"
}
